# -*- coding: utf-8 -*-
"""Copy of streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hzwxfo0nAJnk74gelfX7DNRO9lBzOokH
"""

import streamlit as st
import pandas as pd

from difflib import get_close_matches

# Load knowledge base
kb = pd.read_csv("knowledge_base.csv")

# Function to get answer from KB
def get_answer(user_question):
    questions = kb["question"].tolist()
    match = get_close_matches(user_question, questions, n=1, cutoff=0.5)
    if match:
        return kb[kb["question"] == match[0]]["answer"].values[0]
    else:
        return "Sorry, I don’t have an answer for that yet."

# Streamlit UI
st.title("Project/Program Manager Interview Chatbot")

# Maintain chat history
if "messages" not in st.session_state:
    st.session_state["messages"] = []

# Display chat history
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# User input
if user_input := st.chat_input("Ask me an interview question..."):
    # Add user message
    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)

 # Get bot response from knowledge base
    response = get_answer(user_input)
    st.session_state.messages.append({"role": "assistant", "content": response})

    with st.chat_message("assistant"):
        st.markdown(response)

# Optional: Add footer disclaimer
st.markdown("---")
st.markdown(
    "🛑 **Disclaimer:** This chatbot does not provide any other questions and answer.",
    unsafe_allow_html=True
)